package com.woniu.answer.mapper;

import com.woniu.answer.entity.Advice;
import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface AdviceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_advice
     *
     * @mbggenerated Sun Feb 16 19:42:10 CST 2020
     */
    int deleteByPrimaryKey(Integer adviceid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_advice
     *
     * @mbggenerated Sun Feb 16 19:42:10 CST 2020
     */
    int insert(Advice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_advice
     *
     * @mbggenerated Sun Feb 16 19:42:10 CST 2020
     */
    Advice selectByPrimaryKey(Integer adviceid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_advice
     *
     * @mbggenerated Sun Feb 16 19:42:10 CST 2020
     */
    List<Advice> selectAll();
    List<Advice> selectPage(@Param("title") String title,@Param("status")String status);
    int updateStatusByKey(int id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_advice
     *
     * @mbggenerated Sun Feb 16 19:42:10 CST 2020
     */
    int updateByPrimaryKey(Advice record);
    
}