package com.woniu.answer.mapper;

import com.woniu.answer.entity.Answer;

import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface AnswerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_answer
     *
     * @mbggenerated Wed Feb 19 02:10:59 CST 2020
     */
    int deleteByPrimaryKey(Integer answerid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_answer
     *
     * @mbggenerated Wed Feb 19 02:10:59 CST 2020
     */
    int insert(Answer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_answer
     *
     * @mbggenerated Wed Feb 19 02:10:59 CST 2020
     */
    Answer selectByPrimaryKey(Integer answerid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_answer
     *
     * @mbggenerated Wed Feb 19 02:10:59 CST 2020
     */
    List<Answer> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_answer
     *
     * @mbggenerated Wed Feb 19 02:10:59 CST 2020
     */
    int updateByPrimaryKey(Answer record);
    List<Answer> selectPage(@Param("answerContent")String answerContent,@Param("title")String title,@Param("status")String status);
    /**
     * 
     * @param id答案的id值
     * @return改变答案是否可见
     */
    int updateStatusByKey(int id);
}