package com.woniu.answer.mapper;

import com.woniu.answer.entity.Cate;

import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface CateMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cate
     *
     * @mbggenerated Wed Feb 12 21:50:13 CST 2020
     */
    int deleteByPrimaryKey(Integer cateid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cate
     *
     * @mbggenerated Wed Feb 12 21:50:13 CST 2020
     */
    int insert(Cate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cate
     *
     * @mbggenerated Wed Feb 12 21:50:13 CST 2020
     */
    Cate selectByPrimaryKey(Integer cateid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cate
     *
     * @mbggenerated Wed Feb 12 21:50:13 CST 2020
     */
    List<Cate> selectAll(@Param("name")String name);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cate
     *
     * @mbggenerated Wed Feb 12 21:50:13 CST 2020
     */
	int updateByPrimaryKey(Cate record);
    
    
}