package com.woniu.answer.mapper;

import com.woniu.answer.entity.Answer;
import com.woniu.answer.entity.Comment;
import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface CommentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_comment
     *
     * @mbggenerated Wed Feb 12 21:50:13 CST 2020
     */
    int deleteByPrimaryKey(Integer commentid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_comment
     *
     * @mbggenerated Wed Feb 12 21:50:13 CST 2020
     */
    int insert(Comment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_comment
     *
     * @mbggenerated Wed Feb 12 21:50:13 CST 2020
     */
    Comment selectByPrimaryKey(Integer commentid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_comment
     *
     * @mbggenerated Wed Feb 12 21:50:13 CST 2020
     */
    List<Comment> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_comment
     *
     * @mbggenerated Wed Feb 12 21:50:13 CST 2020
     */
    int updateByPrimaryKey(Comment record);
    /**
     * 
     * @param id答案的id值
     * @return改变答案是否可见
     */
    int updateStatusByKey(int id);
    List<Comment> selectPage(@Param("answercontent")String answercontent,@Param("content")String content,@Param("status")String status);
}