package com.woniu.answer.mapper;

import com.woniu.answer.entity.Notice;
import com.woniu.answer.entity.User;

import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface NoticeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_notice
     *
     * @mbggenerated Wed Feb 19 02:13:48 CST 2020
     */
    int deleteByPrimaryKey(Integer noticeid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_notice
     *
     * @mbggenerated Wed Feb 19 02:13:48 CST 2020
     */
    int insert(Notice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_notice
     *
     * @mbggenerated Wed Feb 19 02:13:48 CST 2020
     */
    Notice selectByPrimaryKey(Integer noticeid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_notice
     *
     * @mbggenerated Wed Feb 19 02:13:48 CST 2020
     */
    List<Notice> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_notice
     *
     * @mbggenerated Wed Feb 19 02:13:48 CST 2020
     */
    int updateByPrimaryKey(Notice record);
    //根据标题/状态查询
    List<Notice> selectPage(@Param("title") String title
    		,@Param("status") String status);
    //修改状态冻结解冻
    int updateStatusByKey(int id);
}