package com.woniu.answer.mapper;

import com.woniu.answer.entity.Answer;
import com.woniu.answer.entity.Pm;
import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface PmMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pm
     *
     * @mbggenerated Wed Feb 12 21:50:13 CST 2020
     */
    int deleteByPrimaryKey(Integer pmid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pm
     *
     * @mbggenerated Wed Feb 12 21:50:13 CST 2020
     */
    int insert(Pm record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pm
     *
     * @mbggenerated Wed Feb 12 21:50:13 CST 2020
     */
    Pm selectByPrimaryKey(Integer pmid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pm
     *
     * @mbggenerated Wed Feb 12 21:50:13 CST 2020
     */
    List<Pm> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pm
     *
     * @mbggenerated Wed Feb 12 21:50:13 CST 2020
     */
    int updateByPrimaryKey(Pm record);  
    List<Pm> selectPage(@Param("content")String content,@Param("isread")String isread);
    int updateIsreadByKey(int id);
}