package com.woniu.answer.mapper;

import com.woniu.answer.entity.Advice;
import com.woniu.answer.entity.Report;
import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface ReportMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_report
     *
     * @mbggenerated Wed Feb 12 21:50:13 CST 2020
     */
    int deleteByPrimaryKey(Integer reportid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_report
     *
     * @mbggenerated Wed Feb 12 21:50:13 CST 2020
     */
    int insert(Report record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_report
     *
     * @mbggenerated Wed Feb 12 21:50:13 CST 2020
     */
    Report selectByPrimaryKey(Integer reportid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_report
     *
     * @mbggenerated Wed Feb 12 21:50:13 CST 2020
     */
    List<Report> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_report
     *
     * @mbggenerated Wed Feb 12 21:50:13 CST 2020
     */
    int updateByPrimaryKey(Report record);
    List<Report> selectQuestionPage(@Param("reportcontent") String reportcontent,@Param("title") String title,@Param("status")String status);
    List<Report> selectAnswerPage(@Param("reportcontent") String reportcontent,@Param("answercontent") String answercontent,@Param("status")String status);
    List<Report> selectCommentPage(@Param("reportcontent") String reportcontent,@Param("content") String content,@Param("status")String status);
    int updateStatusByKey(int id);

}