package com.woniu.answer.mapper;

import com.woniu.answer.entity.User;

import java.util.Date;
import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface UserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbggenerated Wed Feb 12 21:50:13 CST 2020
     */
    int deleteByPrimaryKey(Integer userid);
    int insert(User record);
    User selectByPrimaryKey(Integer userid);
    List<User> selectAll();
    int updateByPrimaryKey(User record);
    //根据用户名查询
    List<User> selectPage(@Param("username") String username
    		,@Param("status") String status
    		,@Param("sex") String sex);
    //修改用户状态冻结解冻modifyDate
    int freezeStatusByKey(@Param("userid")int userid);
    int unFreezeStatusByKey(@Param("userid")int userid);
}