package com.woniu.answer.mapper;

import com.woniu.answer.entity.UserLevel;
import java.util.List;

public interface UserLevelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_level
     *
     * @mbggenerated Wed Feb 12 21:50:13 CST 2020
     */
    int deleteByPrimaryKey(Integer levelid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_level
     *
     * @mbggenerated Wed Feb 12 21:50:13 CST 2020
     */
    int insert(UserLevel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_level
     *
     * @mbggenerated Wed Feb 12 21:50:13 CST 2020
     */
    UserLevel selectByPrimaryKey(Integer levelid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_level
     *
     * @mbggenerated Wed Feb 12 21:50:13 CST 2020
     */
    List<UserLevel> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_level
     *
     * @mbggenerated Wed Feb 12 21:50:13 CST 2020
     */
    int updateByPrimaryKey(UserLevel record);
}