package com.woniu.answer.entity;

import java.util.Date;

public class Advice {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_advice.adviceid
     *
     * @mbggenerated Sun Feb 16 19:42:10 CST 2020
     */
    private Integer adviceid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_advice.title
     *
     * @mbggenerated Sun Feb 16 19:42:10 CST 2020
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_advice.conment
     *
     * @mbggenerated Sun Feb 16 19:42:10 CST 2020
     */
    private String conment;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_advice.imgpath
     *
     * @mbggenerated Sun Feb 16 19:42:10 CST 2020
     */
    private String imgpath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_advice.createdate
     *
     * @mbggenerated Sun Feb 16 19:42:10 CST 2020
     */
    private Date createdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_advice.status
     *
     * @mbggenerated Sun Feb 16 19:42:10 CST 2020
     */
    private String status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_advice.adviceid
     *
     * @return the value of t_advice.adviceid
     *
     * @mbggenerated Sun Feb 16 19:42:10 CST 2020
     */
    public Integer getAdviceid() {
        return adviceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_advice.adviceid
     *
     * @param adviceid the value for t_advice.adviceid
     *
     * @mbggenerated Sun Feb 16 19:42:10 CST 2020
     */
    public void setAdviceid(Integer adviceid) {
        this.adviceid = adviceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_advice.title
     *
     * @return the value of t_advice.title
     *
     * @mbggenerated Sun Feb 16 19:42:10 CST 2020
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_advice.title
     *
     * @param title the value for t_advice.title
     *
     * @mbggenerated Sun Feb 16 19:42:10 CST 2020
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_advice.conment
     *
     * @return the value of t_advice.conment
     *
     * @mbggenerated Sun Feb 16 19:42:10 CST 2020
     */
    public String getConment() {
        return conment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_advice.conment
     *
     * @param conment the value for t_advice.conment
     *
     * @mbggenerated Sun Feb 16 19:42:10 CST 2020
     */
    public void setConment(String conment) {
        this.conment = conment == null ? null : conment.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_advice.imgpath
     *
     * @return the value of t_advice.imgpath
     *
     * @mbggenerated Sun Feb 16 19:42:10 CST 2020
     */
    public String getImgpath() {
        return imgpath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_advice.imgpath
     *
     * @param imgpath the value for t_advice.imgpath
     *
     * @mbggenerated Sun Feb 16 19:42:10 CST 2020
     */
    public void setImgpath(String imgpath) {
        this.imgpath = imgpath == null ? null : imgpath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_advice.createdate
     *
     * @return the value of t_advice.createdate
     *
     * @mbggenerated Sun Feb 16 19:42:10 CST 2020
     */
    public Date getCreatedate() {
        return createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_advice.createdate
     *
     * @param createdate the value for t_advice.createdate
     *
     * @mbggenerated Sun Feb 16 19:42:10 CST 2020
     */
    public void setCreatedate(Date createdate) {
        this.createdate = createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_advice.status
     *
     * @return the value of t_advice.status
     *
     * @mbggenerated Sun Feb 16 19:42:10 CST 2020
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_advice.status
     *
     * @param status the value for t_advice.status
     *
     * @mbggenerated Sun Feb 16 19:42:10 CST 2020
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }
}