package com.woniu.answer.entity;

import java.util.Date;

public class Answer {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_answer.answerid
     *
     * @mbggenerated Wed Feb 19 02:10:59 CST 2020
     */
    private Integer answerid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_answer.questionid
     *
     * @mbggenerated Wed Feb 19 02:10:59 CST 2020
     */
    private Integer questionid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_answer.userid
     *
     * @mbggenerated Wed Feb 19 02:10:59 CST 2020
     */
    private Integer userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_answer.answerContent
     *
     * @mbggenerated Wed Feb 19 02:10:59 CST 2020
     */
    private String answercontent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_answer.createDate
     *
     * @mbggenerated Wed Feb 19 02:10:59 CST 2020
     */
    private Date createdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_answer.status
     *
     * @mbggenerated Wed Feb 19 02:10:59 CST 2020
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_answer.likedCount
     *
     * @mbggenerated Wed Feb 19 02:10:59 CST 2020
     */
    private Integer likedcount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_answer.isanonymous
     *
     * @mbggenerated Wed Feb 19 02:10:59 CST 2020
     */
    private String isanonymous;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_answer.answerid
     *
     * @return the value of t_answer.answerid
     *
     * @mbggenerated Wed Feb 19 02:10:59 CST 2020
     */
    private String username;
    public String getUsername() {
		return username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getTitle() {
		return title;
	}

	public void setTitle(String title) {
		this.title = title;
	}
	/**
	 * title是问题question的标题
	 */
	private String title;
    public Integer getAnswerid() {
        return answerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_answer.answerid
     *
     * @param answerid the value for t_answer.answerid
     *
     * @mbggenerated Wed Feb 19 02:10:59 CST 2020
     */
    public void setAnswerid(Integer answerid) {
        this.answerid = answerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_answer.questionid
     *
     * @return the value of t_answer.questionid
     *
     * @mbggenerated Wed Feb 19 02:10:59 CST 2020
     */
    public Integer getQuestionid() {
        return questionid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_answer.questionid
     *
     * @param questionid the value for t_answer.questionid
     *
     * @mbggenerated Wed Feb 19 02:10:59 CST 2020
     */
    public void setQuestionid(Integer questionid) {
        this.questionid = questionid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_answer.userid
     *
     * @return the value of t_answer.userid
     *
     * @mbggenerated Wed Feb 19 02:10:59 CST 2020
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_answer.userid
     *
     * @param userid the value for t_answer.userid
     *
     * @mbggenerated Wed Feb 19 02:10:59 CST 2020
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_answer.answerContent
     *
     * @return the value of t_answer.answerContent
     *
     * @mbggenerated Wed Feb 19 02:10:59 CST 2020
     */
    public String getAnswercontent() {
        return answercontent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_answer.answerContent
     *
     * @param answercontent the value for t_answer.answerContent
     *
     * @mbggenerated Wed Feb 19 02:10:59 CST 2020
     */
    public void setAnswercontent(String answercontent) {
        this.answercontent = answercontent == null ? null : answercontent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_answer.createDate
     *
     * @return the value of t_answer.createDate
     *
     * @mbggenerated Wed Feb 19 02:10:59 CST 2020
     */
    public Date getCreatedate() {
        return createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_answer.createDate
     *
     * @param createdate the value for t_answer.createDate
     *
     * @mbggenerated Wed Feb 19 02:10:59 CST 2020
     */
    public void setCreatedate(Date createdate) {
        this.createdate = createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_answer.status
     *
     * @return the value of t_answer.status
     *
     * @mbggenerated Wed Feb 19 02:10:59 CST 2020
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_answer.status
     *
     * @param status the value for t_answer.status
     *
     * @mbggenerated Wed Feb 19 02:10:59 CST 2020
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_answer.likedCount
     *
     * @return the value of t_answer.likedCount
     *
     * @mbggenerated Wed Feb 19 02:10:59 CST 2020
     */
    public Integer getLikedcount() {
        return likedcount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_answer.likedCount
     *
     * @param likedcount the value for t_answer.likedCount
     *
     * @mbggenerated Wed Feb 19 02:10:59 CST 2020
     */
    public void setLikedcount(Integer likedcount) {
        this.likedcount = likedcount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_answer.isanonymous
     *
     * @return the value of t_answer.isanonymous
     *
     * @mbggenerated Wed Feb 19 02:10:59 CST 2020
     */
    public String getIsanonymous() {
        return isanonymous;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_answer.isanonymous
     *
     * @param isanonymous the value for t_answer.isanonymous
     *
     * @mbggenerated Wed Feb 19 02:10:59 CST 2020
     */
    public void setIsanonymous(String isanonymous) {
        this.isanonymous = isanonymous == null ? null : isanonymous.trim();
    }
}