package com.woniu.answer.entity;

public class Cate {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cate.cateid
     *
     * @mbggenerated Wed Feb 12 21:50:13 CST 2020
     */
    private Integer cateid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cate.catename
     *
     * @mbggenerated Wed Feb 12 21:50:13 CST 2020
     */
    private String catename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cate.description
     *
     * @mbggenerated Wed Feb 12 21:50:13 CST 2020
     */
    private String description;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cate.cateid
     *
     * @return the value of t_cate.cateid
     *
     * @mbggenerated Wed Feb 12 21:50:13 CST 2020
     */
    public Integer getCateid() {
        return cateid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cate.cateid
     *
     * @param cateid the value for t_cate.cateid
     *
     * @mbggenerated Wed Feb 12 21:50:13 CST 2020
     */
    public void setCateid(Integer cateid) {
        this.cateid = cateid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cate.catename
     *
     * @return the value of t_cate.catename
     *
     * @mbggenerated Wed Feb 12 21:50:13 CST 2020
     */
    public String getCatename() {
        return catename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cate.catename
     *
     * @param catename the value for t_cate.catename
     *
     * @mbggenerated Wed Feb 12 21:50:13 CST 2020
     */
    public void setCatename(String catename) {
        this.catename = catename == null ? null : catename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cate.description
     *
     * @return the value of t_cate.description
     *
     * @mbggenerated Wed Feb 12 21:50:13 CST 2020
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cate.description
     *
     * @param description the value for t_cate.description
     *
     * @mbggenerated Wed Feb 12 21:50:13 CST 2020
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

	@Override
	public String toString() {
		return "Cate [cateid=" + cateid + ", catename=" + catename + ", description=" + description + "]";
	}
}