package com.woniu.answer.entity;

import java.util.Date;

public class Comment {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_comment.commentid
     *
     * @mbggenerated Wed Feb 12 21:50:13 CST 2020
     */
    private Integer commentid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_comment.answerid
     *
     * @mbggenerated Wed Feb 12 21:50:13 CST 2020
     */
    private Integer answerid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_comment.content
     *
     * @mbggenerated Wed Feb 12 21:50:13 CST 2020
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_comment.userid
     *
     * @mbggenerated Wed Feb 12 21:50:13 CST 2020
     */
    private Integer userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_comment.createDate
     *
     * @mbggenerated Wed Feb 12 21:50:13 CST 2020
     */
    private Date createdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_comment.status
     *
     * @mbggenerated Wed Feb 12 21:50:13 CST 2020
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_comment.likedCount
     *
     * @mbggenerated Wed Feb 12 21:50:13 CST 2020
     */
    private Integer likedcount;
    private String answercontent;
  
	public String getAnswercontent() {
		return answercontent;
	}

	public void setAnswercontent(String answercontent) {
		this.answercontent = answercontent;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_comment.commentid
     *
     * @return the value of t_comment.commentid
     *
     * @mbggenerated Wed Feb 12 21:50:13 CST 2020
     */
    public Integer getCommentid() {
        return commentid;
    }
    private String username;
    public String getUsername() {
		return username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_comment.commentid
     *
     * @param commentid the value for t_comment.commentid
     *
     * @mbggenerated Wed Feb 12 21:50:13 CST 2020
     */
    public void setCommentid(Integer commentid) {
        this.commentid = commentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_comment.answerid
     *
     * @return the value of t_comment.answerid
     *
     * @mbggenerated Wed Feb 12 21:50:13 CST 2020
     */
    public Integer getAnswerid() {
        return answerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_comment.answerid
     *
     * @param answerid the value for t_comment.answerid
     *
     * @mbggenerated Wed Feb 12 21:50:13 CST 2020
     */
    public void setAnswerid(Integer answerid) {
        this.answerid = answerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_comment.content
     *
     * @return the value of t_comment.content
     *
     * @mbggenerated Wed Feb 12 21:50:13 CST 2020
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_comment.content
     *
     * @param content the value for t_comment.content
     *
     * @mbggenerated Wed Feb 12 21:50:13 CST 2020
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_comment.userid
     *
     * @return the value of t_comment.userid
     *
     * @mbggenerated Wed Feb 12 21:50:13 CST 2020
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_comment.userid
     *
     * @param userid the value for t_comment.userid
     *
     * @mbggenerated Wed Feb 12 21:50:13 CST 2020
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_comment.createDate
     *
     * @return the value of t_comment.createDate
     *
     * @mbggenerated Wed Feb 12 21:50:13 CST 2020
     */
    public Date getCreatedate() {
        return createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_comment.createDate
     *
     * @param createdate the value for t_comment.createDate
     *
     * @mbggenerated Wed Feb 12 21:50:13 CST 2020
     */
    public void setCreatedate(Date createdate) {
        this.createdate = createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_comment.status
     *
     * @return the value of t_comment.status
     *
     * @mbggenerated Wed Feb 12 21:50:13 CST 2020
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_comment.status
     *
     * @param status the value for t_comment.status
     *
     * @mbggenerated Wed Feb 12 21:50:13 CST 2020
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_comment.likedCount
     *
     * @return the value of t_comment.likedCount
     *
     * @mbggenerated Wed Feb 12 21:50:13 CST 2020
     */
    public Integer getLikedcount() {
        return likedcount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_comment.likedCount
     *
     * @param likedcount the value for t_comment.likedCount
     *
     * @mbggenerated Wed Feb 12 21:50:13 CST 2020
     */
    public void setLikedcount(Integer likedcount) {
        this.likedcount = likedcount;
    }
}