package com.woniu.answer.entity;

import java.util.Date;

public class Notice {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_notice.noticeid
     *
     * @mbggenerated Wed Feb 19 02:13:48 CST 2020
     */
    private Integer noticeid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_notice.title
     *
     * @mbggenerated Wed Feb 19 02:13:48 CST 2020
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_notice.content
     *
     * @mbggenerated Wed Feb 19 02:13:48 CST 2020
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_notice.imgpath
     *
     * @mbggenerated Wed Feb 19 02:13:48 CST 2020
     */
    private String imgpath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_notice.createdate
     *
     * @mbggenerated Wed Feb 19 02:13:48 CST 2020
     */
    private Date createdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_notice.modifydate
     *
     * @mbggenerated Wed Feb 19 02:13:48 CST 2020
     */
    private Date modifydate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_notice.status
     *
     * @mbggenerated Wed Feb 19 02:13:48 CST 2020
     */
    private String status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_notice.noticeid
     *
     * @return the value of t_notice.noticeid
     *
     * @mbggenerated Wed Feb 19 02:13:48 CST 2020
     */
    public Integer getNoticeid() {
        return noticeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_notice.noticeid
     *
     * @param noticeid the value for t_notice.noticeid
     *
     * @mbggenerated Wed Feb 19 02:13:48 CST 2020
     */
    public void setNoticeid(Integer noticeid) {
        this.noticeid = noticeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_notice.title
     *
     * @return the value of t_notice.title
     *
     * @mbggenerated Wed Feb 19 02:13:48 CST 2020
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_notice.title
     *
     * @param title the value for t_notice.title
     *
     * @mbggenerated Wed Feb 19 02:13:48 CST 2020
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_notice.content
     *
     * @return the value of t_notice.content
     *
     * @mbggenerated Wed Feb 19 02:13:48 CST 2020
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_notice.content
     *
     * @param content the value for t_notice.content
     *
     * @mbggenerated Wed Feb 19 02:13:48 CST 2020
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_notice.imgpath
     *
     * @return the value of t_notice.imgpath
     *
     * @mbggenerated Wed Feb 19 02:13:48 CST 2020
     */
    public String getImgpath() {
        return imgpath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_notice.imgpath
     *
     * @param imgpath the value for t_notice.imgpath
     *
     * @mbggenerated Wed Feb 19 02:13:48 CST 2020
     */
    public void setImgpath(String imgpath) {
        this.imgpath = imgpath == null ? null : imgpath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_notice.createdate
     *
     * @return the value of t_notice.createdate
     *
     * @mbggenerated Wed Feb 19 02:13:48 CST 2020
     */
    public Date getCreatedate() {
        return createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_notice.createdate
     *
     * @param createdate the value for t_notice.createdate
     *
     * @mbggenerated Wed Feb 19 02:13:48 CST 2020
     */
    public void setCreatedate(Date createdate) {
        this.createdate = createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_notice.modifydate
     *
     * @return the value of t_notice.modifydate
     *
     * @mbggenerated Wed Feb 19 02:13:48 CST 2020
     */
    public Date getModifydate() {
        return modifydate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_notice.modifydate
     *
     * @param modifydate the value for t_notice.modifydate
     *
     * @mbggenerated Wed Feb 19 02:13:48 CST 2020
     */
    public void setModifydate(Date modifydate) {
        this.modifydate = modifydate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_notice.status
     *
     * @return the value of t_notice.status
     *
     * @mbggenerated Wed Feb 19 02:13:48 CST 2020
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_notice.status
     *
     * @param status the value for t_notice.status
     *
     * @mbggenerated Wed Feb 19 02:13:48 CST 2020
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }
}