package com.woniu.answer.entity;

public class UserLevel {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_level.levelid
     *
     * @mbggenerated Wed Feb 12 21:50:13 CST 2020
     */
    private Integer levelid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_level.levelName
     *
     * @mbggenerated Wed Feb 12 21:50:13 CST 2020
     */
    private String levelname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_level.description
     *
     * @mbggenerated Wed Feb 12 21:50:13 CST 2020
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_level.minDegree
     *
     * @mbggenerated Wed Feb 12 21:50:13 CST 2020
     */
    private Integer mindegree;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_level.maxDegree
     *
     * @mbggenerated Wed Feb 12 21:50:13 CST 2020
     */
    private Integer maxdegree;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_level.levelid
     *
     * @return the value of t_level.levelid
     *
     * @mbggenerated Wed Feb 12 21:50:13 CST 2020
     */
    public Integer getLevelid() {
        return levelid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_level.levelid
     *
     * @param levelid the value for t_level.levelid
     *
     * @mbggenerated Wed Feb 12 21:50:13 CST 2020
     */
    public void setLevelid(Integer levelid) {
        this.levelid = levelid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_level.levelName
     *
     * @return the value of t_level.levelName
     *
     * @mbggenerated Wed Feb 12 21:50:13 CST 2020
     */
    public String getLevelname() {
        return levelname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_level.levelName
     *
     * @param levelname the value for t_level.levelName
     *
     * @mbggenerated Wed Feb 12 21:50:13 CST 2020
     */
    public void setLevelname(String levelname) {
        this.levelname = levelname == null ? null : levelname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_level.description
     *
     * @return the value of t_level.description
     *
     * @mbggenerated Wed Feb 12 21:50:13 CST 2020
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_level.description
     *
     * @param description the value for t_level.description
     *
     * @mbggenerated Wed Feb 12 21:50:13 CST 2020
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_level.minDegree
     *
     * @return the value of t_level.minDegree
     *
     * @mbggenerated Wed Feb 12 21:50:13 CST 2020
     */
    public Integer getMindegree() {
        return mindegree;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_level.minDegree
     *
     * @param mindegree the value for t_level.minDegree
     *
     * @mbggenerated Wed Feb 12 21:50:13 CST 2020
     */
    public void setMindegree(Integer mindegree) {
        this.mindegree = mindegree;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_level.maxDegree
     *
     * @return the value of t_level.maxDegree
     *
     * @mbggenerated Wed Feb 12 21:50:13 CST 2020
     */
    public Integer getMaxdegree() {
        return maxdegree;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_level.maxDegree
     *
     * @param maxdegree the value for t_level.maxDegree
     *
     * @mbggenerated Wed Feb 12 21:50:13 CST 2020
     */
    public void setMaxdegree(Integer maxdegree) {
        this.maxdegree = maxdegree;
    }
}