package com.woniu.answer.entity;

import java.util.Date;

public class User {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.userid
     *
     * @mbggenerated Wed Feb 12 21:50:13 CST 2020
     */
    private Integer userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.username
     *
     * @mbggenerated Wed Feb 12 21:50:13 CST 2020
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.password
     *
     * @mbggenerated Wed Feb 12 21:50:13 CST 2020
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.realName
     *
     * @mbggenerated Wed Feb 12 21:50:13 CST 2020
     */
    private String realname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.birthday
     *
     * @mbggenerated Wed Feb 12 21:50:13 CST 2020
     */
    private Date birthday;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.sex
     *
     * @mbggenerated Wed Feb 12 21:50:13 CST 2020
     */
    private String sex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.degree
     *
     * @mbggenerated Wed Feb 12 21:50:13 CST 2020
     */
    private Integer degree;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.money
     *
     * @mbggenerated Wed Feb 12 21:50:13 CST 2020
     */
    private Double money;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.headerImg
     *
     * @mbggenerated Wed Feb 12 21:50:13 CST 2020
     */
    private String headerimg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.userLabel
     *
     * @mbggenerated Wed Feb 12 21:50:13 CST 2020
     */
    private String userlabel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.tel
     *
     * @mbggenerated Wed Feb 12 21:50:13 CST 2020
     */
    private String tel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.email
     *
     * @mbggenerated Wed Feb 12 21:50:13 CST 2020
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.status
     *
     * @mbggenerated Wed Feb 12 21:50:13 CST 2020
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.createDate
     *
     * @mbggenerated Wed Feb 12 21:50:13 CST 2020
     */
    private Date createdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.modifyDate
     *
     * @mbggenerated Wed Feb 12 21:50:13 CST 2020
     */
    private Date modifydate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.nickname
     *
     * @mbggenerated Wed Feb 12 21:50:13 CST 2020
     */
    private String nickname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.profession
     *
     * @mbggenerated Wed Feb 12 21:50:13 CST 2020
     */
    private String profession;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.questionCount
     *
     * @mbggenerated Wed Feb 12 21:50:13 CST 2020
     */
    private Integer questioncount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.answerCount
     *
     * @mbggenerated Wed Feb 12 21:50:13 CST 2020
     */
    private Integer answercount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.levelid
     *
     * @mbggenerated Wed Feb 12 21:50:13 CST 2020
     */
    private Integer levelid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.likedCount
     *
     * @mbggenerated Wed Feb 12 21:50:13 CST 2020
     */
    private Integer likedcount;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.userid
     *
     * @return the value of t_user.userid
     *
     * @mbggenerated Wed Feb 12 21:50:13 CST 2020
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.userid
     *
     * @param userid the value for t_user.userid
     *
     * @mbggenerated Wed Feb 12 21:50:13 CST 2020
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.username
     *
     * @return the value of t_user.username
     *
     * @mbggenerated Wed Feb 12 21:50:13 CST 2020
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.username
     *
     * @param username the value for t_user.username
     *
     * @mbggenerated Wed Feb 12 21:50:13 CST 2020
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.password
     *
     * @return the value of t_user.password
     *
     * @mbggenerated Wed Feb 12 21:50:13 CST 2020
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.password
     *
     * @param password the value for t_user.password
     *
     * @mbggenerated Wed Feb 12 21:50:13 CST 2020
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.realName
     *
     * @return the value of t_user.realName
     *
     * @mbggenerated Wed Feb 12 21:50:13 CST 2020
     */
    public String getRealname() {
        return realname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.realName
     *
     * @param realname the value for t_user.realName
     *
     * @mbggenerated Wed Feb 12 21:50:13 CST 2020
     */
    public void setRealname(String realname) {
        this.realname = realname == null ? null : realname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.birthday
     *
     * @return the value of t_user.birthday
     *
     * @mbggenerated Wed Feb 12 21:50:13 CST 2020
     */
    public Date getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.birthday
     *
     * @param birthday the value for t_user.birthday
     *
     * @mbggenerated Wed Feb 12 21:50:13 CST 2020
     */
    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.sex
     *
     * @return the value of t_user.sex
     *
     * @mbggenerated Wed Feb 12 21:50:13 CST 2020
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.sex
     *
     * @param sex the value for t_user.sex
     *
     * @mbggenerated Wed Feb 12 21:50:13 CST 2020
     */
    public void setSex(String sex) {
        this.sex = sex == null ? null : sex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.degree
     *
     * @return the value of t_user.degree
     *
     * @mbggenerated Wed Feb 12 21:50:13 CST 2020
     */
    public Integer getDegree() {
        return degree;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.degree
     *
     * @param degree the value for t_user.degree
     *
     * @mbggenerated Wed Feb 12 21:50:13 CST 2020
     */
    public void setDegree(Integer degree) {
        this.degree = degree;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.money
     *
     * @return the value of t_user.money
     *
     * @mbggenerated Wed Feb 12 21:50:13 CST 2020
     */
    public Double getMoney() {
        return money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.money
     *
     * @param money the value for t_user.money
     *
     * @mbggenerated Wed Feb 12 21:50:13 CST 2020
     */
    public void setMoney(Double money) {
        this.money = money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.headerImg
     *
     * @return the value of t_user.headerImg
     *
     * @mbggenerated Wed Feb 12 21:50:13 CST 2020
     */
    public String getHeaderimg() {
        return headerimg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.headerImg
     *
     * @param headerimg the value for t_user.headerImg
     *
     * @mbggenerated Wed Feb 12 21:50:13 CST 2020
     */
    public void setHeaderimg(String headerimg) {
        this.headerimg = headerimg == null ? null : headerimg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.userLabel
     *
     * @return the value of t_user.userLabel
     *
     * @mbggenerated Wed Feb 12 21:50:13 CST 2020
     */
    public String getUserlabel() {
        return userlabel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.userLabel
     *
     * @param userlabel the value for t_user.userLabel
     *
     * @mbggenerated Wed Feb 12 21:50:13 CST 2020
     */
    public void setUserlabel(String userlabel) {
        this.userlabel = userlabel == null ? null : userlabel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.tel
     *
     * @return the value of t_user.tel
     *
     * @mbggenerated Wed Feb 12 21:50:13 CST 2020
     */
    public String getTel() {
        return tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.tel
     *
     * @param tel the value for t_user.tel
     *
     * @mbggenerated Wed Feb 12 21:50:13 CST 2020
     */
    public void setTel(String tel) {
        this.tel = tel == null ? null : tel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.email
     *
     * @return the value of t_user.email
     *
     * @mbggenerated Wed Feb 12 21:50:13 CST 2020
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.email
     *
     * @param email the value for t_user.email
     *
     * @mbggenerated Wed Feb 12 21:50:13 CST 2020
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.status
     *
     * @return the value of t_user.status
     *
     * @mbggenerated Wed Feb 12 21:50:13 CST 2020
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.status
     *
     * @param status the value for t_user.status
     *
     * @mbggenerated Wed Feb 12 21:50:13 CST 2020
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.createDate
     *
     * @return the value of t_user.createDate
     *
     * @mbggenerated Wed Feb 12 21:50:13 CST 2020
     */
    public Date getCreatedate() {
        return createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.createDate
     *
     * @param createdate the value for t_user.createDate
     *
     * @mbggenerated Wed Feb 12 21:50:13 CST 2020
     */
    public void setCreatedate(Date createdate) {
        this.createdate = createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.modifyDate
     *
     * @return the value of t_user.modifyDate
     *
     * @mbggenerated Wed Feb 12 21:50:13 CST 2020
     */
    public Date getModifydate() {
        return modifydate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.modifyDate
     *
     * @param modifydate the value for t_user.modifyDate
     *
     * @mbggenerated Wed Feb 12 21:50:13 CST 2020
     */
    public void setModifydate(Date modifydate) {
        this.modifydate = modifydate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.nickname
     *
     * @return the value of t_user.nickname
     *
     * @mbggenerated Wed Feb 12 21:50:13 CST 2020
     */
    public String getNickname() {
        return nickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.nickname
     *
     * @param nickname the value for t_user.nickname
     *
     * @mbggenerated Wed Feb 12 21:50:13 CST 2020
     */
    public void setNickname(String nickname) {
        this.nickname = nickname == null ? null : nickname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.profession
     *
     * @return the value of t_user.profession
     *
     * @mbggenerated Wed Feb 12 21:50:13 CST 2020
     */
    public String getProfession() {
        return profession;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.profession
     *
     * @param profession the value for t_user.profession
     *
     * @mbggenerated Wed Feb 12 21:50:13 CST 2020
     */
    public void setProfession(String profession) {
        this.profession = profession == null ? null : profession.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.questionCount
     *
     * @return the value of t_user.questionCount
     *
     * @mbggenerated Wed Feb 12 21:50:13 CST 2020
     */
    public Integer getQuestioncount() {
        return questioncount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.questionCount
     *
     * @param questioncount the value for t_user.questionCount
     *
     * @mbggenerated Wed Feb 12 21:50:13 CST 2020
     */
    public void setQuestioncount(Integer questioncount) {
        this.questioncount = questioncount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.answerCount
     *
     * @return the value of t_user.answerCount
     *
     * @mbggenerated Wed Feb 12 21:50:13 CST 2020
     */
    public Integer getAnswercount() {
        return answercount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.answerCount
     *
     * @param answercount the value for t_user.answerCount
     *
     * @mbggenerated Wed Feb 12 21:50:13 CST 2020
     */
    public void setAnswercount(Integer answercount) {
        this.answercount = answercount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.levelid
     *
     * @return the value of t_user.levelid
     *
     * @mbggenerated Wed Feb 12 21:50:13 CST 2020
     */
    public Integer getLevelid() {
        return levelid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.levelid
     *
     * @param levelid the value for t_user.levelid
     *
     * @mbggenerated Wed Feb 12 21:50:13 CST 2020
     */
    public void setLevelid(Integer levelid) {
        this.levelid = levelid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.likedCount
     *
     * @return the value of t_user.likedCount
     *
     * @mbggenerated Wed Feb 12 21:50:13 CST 2020
     */
    public Integer getLikedcount() {
        return likedcount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.likedCount
     *
     * @param likedcount the value for t_user.likedCount
     *
     * @mbggenerated Wed Feb 12 21:50:13 CST 2020
     */
    public void setLikedcount(Integer likedcount) {
        this.likedcount = likedcount;
    }
}